Paste the hak

diff --git a/package/base-files/files/sbin/sysupgrade b/package/base-files/files/sbin/sysupgrade
--- a/package/base-files/files/sbin/sysupgrade
+++ b/package/base-files/files/sbin/sysupgrade
@@ -1,19 +1,16 @@
 #!/bin/sh
-
 . /lib/functions.sh
 . /lib/functions/system.sh
 
 # initialize defaults
-export MTD_ARGS=""
+RAMFS_COPY_BIN=""	# extra programs for temporary ramfs root
+RAMFS_COPY_DATA=""	# extra data files
 export MTD_CONFIG_ARGS=""
 export INTERACTIVE=0
 export VERBOSE=1
 export SAVE_CONFIG=1
 export SAVE_OVERLAY=0
-export SAVE_OVERLAY_PATH=
-export SAVE_PARTITIONS=1
-export SAVE_INSTALLED_PKGS=0
-export SKIP_UNCHANGED=0
+export DELAY=
 export CONF_IMAGE=
 export CONF_BACKUP_LIST=0
 export CONF_BACKUP=
@@ -22,29 +19,25 @@ export NEED_IMAGE=
 export HELP=0
 export FORCE=0
 export TEST=0
-export UMOUNT_ETCBACKUP_DIR=0
 
 # parse options
 while [ -n "$1" ]; do
 	case "$1" in
 		-i) export INTERACTIVE=1;;
+		-d) export DELAY="$2"; shift;;
 		-v) export VERBOSE="$(($VERBOSE + 1))";;
 		-q) export VERBOSE="$(($VERBOSE - 1))";;
 		-n) export SAVE_CONFIG=0;;
-		-c) export SAVE_OVERLAY=1 SAVE_OVERLAY_PATH=/etc;;
-		-o) export SAVE_OVERLAY=1 SAVE_OVERLAY_PATH=/;;
-		-p) export SAVE_PARTITIONS=0;;
-		-k) export SAVE_INSTALLED_PKGS=1;;
-		-u) export SKIP_UNCHANGED=1;;
+		-c) export SAVE_OVERLAY=1;;
 		-b|--create-backup) export CONF_BACKUP="$2" NEED_IMAGE=1; shift;;
 		-r|--restore-backup) export CONF_RESTORE="$2" NEED_IMAGE=1; shift;;
-		-l|--list-backup) export CONF_BACKUP_LIST=1;;
+		-l|--list-backup) export CONF_BACKUP_LIST=1; break;;
 		-f) export CONF_IMAGE="$2"; shift;;
 		-F|--force) export FORCE=1;;
 		-T|--test) export TEST=1;;
 		-h|--help) export HELP=1; break;;
 		-*)
-			echo "Invalid option: $1" >&2
+			echo "Invalid option: $1"
 			exit 1
 		;;
 		*) break;;
@@ -54,27 +47,21 @@ done
 
 export CONFFILES=/tmp/sysupgrade.conffiles
 export CONF_TAR=/tmp/sysupgrade.tgz
-export ETCBACKUP_DIR=/etc/backup
-export INSTALLED_PACKAGES=${ETCBACKUP_DIR}/installed_packages.txt
 
-IMAGE="$1"
+export ARGV="$*"
+export ARGC="$#"
 
-[ -z "$IMAGE" -a -z "$NEED_IMAGE" -a $CONF_BACKUP_LIST -eq 0 -o $HELP -gt 0 ] && {
+[ -z "$ARGV" -a -z "$NEED_IMAGE" -o $HELP -gt 0 ] && {
 	cat <<EOF
 Usage: $0 [<upgrade-option>...] <image file or URL>
-       $0 [-q] [-i] [-c] [-u] [-o] [-k] <backup-command> <file>
+       $0 [-q] [-i] <backup-command> <file>
 
 upgrade-option:
+	-d <delay>   add a delay before rebooting
 	-f <config>  restore configuration from .tar.gz (file or url)
 	-i           interactive mode
 	-c           attempt to preserve all changed files in /etc/
-	-o           attempt to preserve all changed files in /, except those
-	             from packages but including changed confs.
-	-u           skip from backup files that are equal to those in /rom
 	-n           do not save configuration over reflash
-	-p           do not attempt to restore the partition table after flash.
-	-k           include in backup a list of current installed packages at
-	             $INSTALLED_PACKAGES
 	-T | --test
 	             Verify image and config .tar.gz but do not actually flash.
 	-F | --force
@@ -100,7 +87,7 @@ EOF
 	exit 1
 }
 
-[ -n "$IMAGE" -a -n "$NEED_IMAGE" ] && {
+[ -n "$ARGV" -a -n "$NEED_IMAGE" ] && {
 	cat <<-EOF
 		-b|--create-backup and -r|--restore-backup do not perform a firmware upgrade.
 		Do not specify both -b|-r and a firmware image.
@@ -111,162 +98,61 @@ EOF
 # prevent messages from clobbering the tarball when using stdout
 [ "$CONF_BACKUP" = "-" ] && export VERBOSE=0
 
-
-list_conffiles() {
-	awk '
-		BEGIN { conffiles = 0 }
-		/^Conffiles:/ { conffiles = 1; next }
-		!/^ / { conffiles = 0; next }
-		conffiles == 1 { print }
-	' /usr/lib/opkg/status
-}
-
-list_changed_conffiles() {
-	# Cannot handle spaces in filenames - but opkg cannot either...
-	list_conffiles | while read file csum; do
-		[ -r "$file" ] || continue
-
-		echo "${csum}  ${file}" | sha256sum -sc - || echo "$file"
-	done
-}
-
-add_conffiles() {
+add_uci_conffiles() {
 	local file="$1"
 	( find $(sed -ne '/^[[:space:]]*$/d; /^#/d; p' \
 		/etc/sysupgrade.conf /lib/upgrade/keep.d/* 2>/dev/null) \
-		\( -type f -o -type l \) $find_filter 2>/dev/null;
-	  list_changed_conffiles ) | sort -u > "$file"
+		-type f -o -type l 2>/dev/null;
+	  opkg list-changed-conffiles ) | sort -u > "$file"
 	return 0
 }
 
 add_overlayfiles() {
 	local file="$1"
-
-	local packagesfiles=$1.packagesfiles
-	touch "$packagesfiles"
-
-	if [ "$SAVE_OVERLAY_PATH" = / ]; then
-		local conffiles=$1.conffiles
-		local keepfiles=$1.keepfiles
-
-		list_conffiles | cut -f2 -d ' ' | sort -u > "$conffiles"
-
-		# backup files from /etc/sysupgrade.conf and /lib/upgrade/keep.d, but
-		# ignore those aready controlled by opkg conffiles
-		find $(sed -ne '/^[[:space:]]*$/d; /^#/d; p' \
-			/etc/sysupgrade.conf /lib/upgrade/keep.d/* 2>/dev/null) \
-			\( -type f -o -type l \) 2>/dev/null | sort -u |
-			grep -h -v -x -F -f $conffiles > "$keepfiles"
-
-		# backup conffiles, but only those changed if '-u'
-		[ $SKIP_UNCHANGED = 1 ] &&
-			list_changed_conffiles | sort -u > "$conffiles"
-
-		# do not backup files from packages, except those listed
-		# in conffiles and keep.d
-		{
-			find /usr/lib/opkg/info -type f -name "*.list" -exec cat {} \;
-			find /usr/lib/opkg/info -type f -name "*.control" -exec sed \
-				-ne '/^Alternatives/{s/^Alternatives: //;s/, /\n/g;p}' {} \; |
-				cut -f2 -d:
-		} |  grep -v -x -F -f $conffiles |
-		     grep -v -x -F -f $keepfiles | sort -u > "$packagesfiles"
-		rm -f "$keepfiles" "$conffiles"
+	if [ -d /overlay/upper ]; then
+		local overlaydir="/overlay/upper"
+	else
+		local overlaydir="/overlay"
 	fi
-
-	# busybox grep bug when file is empty
-	[ -s "$packagesfiles" ] || echo > $packagesfiles
-
-	( cd /overlay/upper/; find .$SAVE_OVERLAY_PATH \( -type f -o -type l \) $find_filter | sed \
-		-e 's,^\.,,' \
-		-e '\,^/etc/board.json$,d' \
+	find $overlaydir/etc/ -type f -o -type l | sed \
+		-e 's,^/overlay/,/,' \
+		-e '\,/META_[a-zA-Z0-9]*$,d' \
+		-e '\,/functions.sh$,d' \
 		-e '\,/[^/]*-opkg$,d' \
-		-e '\,^/etc/urandom.seed$,d' \
-		-e "\,^$INSTALLED_PACKAGES$,d" \
-		-e '\,^/usr/lib/opkg/.*,d' \
-	) | grep -v -x -F -f $packagesfiles > "$file"
-
-	rm -f "$packagesfiles"
-
+	> "$file"
 	return 0
 }
 
 # hooks
-sysupgrade_image_check="fwtool_check_signature fwtool_check_image platform_check_image"
-
-if [ $SAVE_OVERLAY = 1 ]; then
-	[ ! -d /overlay/upper/etc ] && {
-		echo "Cannot find '/overlay/upper/etc', required for '-c'" >&2
-		exit 1
-	}
+sysupgrade_image_check="platform_check_image"
+[ $SAVE_OVERLAY = 0 -o ! -d /overlay/etc ] && \
+	sysupgrade_init_conffiles="add_uci_conffiles" || \
 	sysupgrade_init_conffiles="add_overlayfiles"
-else
-	sysupgrade_init_conffiles="add_conffiles"
-fi
-
-find_filter=""
-if [ $SKIP_UNCHANGED = 1 ]; then
-	[ ! -d /rom/ ] && {
-		echo "'/rom/' is required by '-u'"
-		exit 1
-	}
-	find_filter='( ( -exec test -e /rom/{} ; -exec cmp -s /{} /rom/{} ; ) -o -print )'
-fi
 
 include /lib/upgrade
 
+[ "$1" = "nand" ] && nand_upgrade_stage2 $@
+
 do_save_conffiles() {
-	local conf_tar="$1"
+	local conf_tar="${1:-$CONF_TAR}"
 
 	[ -z "$(rootfs_type)" ] && {
-		echo "Cannot save config while running from ramdisk." >&2
+		echo "Cannot save config while running from ramdisk."
 		ask_bool 0 "Abort" && exit
-		rm -f "$conf_tar"
 		return 0
 	}
 	run_hooks "$CONFFILES" $sysupgrade_init_conffiles
 	ask_bool 0 "Edit config file list" && vi "$CONFFILES"
 
-	if [ "$SAVE_INSTALLED_PKGS" -eq 1 ]; then
-		echo "${INSTALLED_PACKAGES}" >> "$CONFFILES"
-		mkdir -p "$ETCBACKUP_DIR"
-		# Avoid touching filesystem on each backup
-		RAMFS="$(mktemp -d -t sysupgrade.XXXXXX)"
-		mkdir -p "$RAMFS/upper" "$RAMFS/work"
-		mount -t overlay overlay -o lowerdir=$ETCBACKUP_DIR,upperdir=$RAMFS/upper,workdir=$RAMFS/work $ETCBACKUP_DIR &&
-			UMOUNT_ETCBACKUP_DIR=1 || {
-				echo "Cannot mount '$ETCBACKUP_DIR' as tmpfs to avoid touching disk while saving the list of installed packages." >&2
-				ask_bool 0 "Abort" && exit
-			}
-
-		# Format: pkg-name<TAB>{rom,overlay,unkown}
-		# rom is used for pkgs in /rom, even if updated later
-		find /usr/lib/opkg/info -name "*.control" \( \
-			\( -exec test -f /rom/{} \; -exec echo {} rom \; \) -o \
-			\( -exec test -f /overlay/upper/{} \; -exec echo {} overlay \; \) -o \
-			\( -exec echo {} unknown \; \) \
-			\) | sed -e 's,.*/,,;s/\.control /\t/' > ${INSTALLED_PACKAGES}
-	fi
-
 	v "Saving config files..."
 	[ "$VERBOSE" -gt 1 ] && TAR_V="v" || TAR_V=""
 	tar c${TAR_V}zf "$conf_tar" -T "$CONFFILES" 2>/dev/null
-	if [ "$?" -ne 0 ]; then
-		echo "Failed to create the configuration backup."
-		rm -f "$conf_tar"
-		exit 1
-	fi
 
-	[ "$UMOUNT_ETCBACKUP_DIR" -eq 1 ] && {
-		umount "$ETCBACKUP_DIR"
-		rm -rf "$RAMFS"
-	}
 	rm -f "$CONFFILES"
 }
 
 if [ $CONF_BACKUP_LIST -eq 1 ]; then
-	run_hooks "$CONFFILES" $sysupgrade_init_conffiles
-	[ "$SAVE_INSTALLED_PKGS" -eq 1 ] && echo ${INSTALLED_PACKAGES} >> "$CONFFILES"
+	add_uci_conffiles "$CONFFILES"
 	cat "$CONFFILES"
 	rm -f "$CONFFILES"
 	exit 0
@@ -279,7 +165,7 @@ fi
 
 if [ -n "$CONF_RESTORE" ]; then
 	if [ "$CONF_RESTORE" != "-" ] && [ ! -f "$CONF_RESTORE" ]; then
-		echo "Backup archive '$CONF_RESTORE' not found." >&2
+		echo "Backup archive '$CONF_RESTORE' not found."
 		exit 1
 	fi
 
@@ -289,43 +175,17 @@ if [ -n "$CONF_RESTORE" ]; then
 fi
 
 type platform_check_image >/dev/null 2>/dev/null || {
-	echo "Firmware upgrade is not implemented for this platform." >&2
+	echo "Firmware upgrade is not implemented for this platform."
 	exit 1
 }
 
-case "$IMAGE" in
-	http://*|\
-	https://*)
-		wget -O/tmp/sysupgrade.img "$IMAGE"
-		IMAGE=/tmp/sysupgrade.img
-		;;
-esac
-
-IMAGE="$(readlink -f "$IMAGE")"
-
-case "$IMAGE" in
-	'')
-		echo "Image file not found." >&2
-		exit 1
-		;;
-	/tmp/*)	;;
-	*)
-		v "Image not in /tmp, copying..."
-		cp -f "$IMAGE" /tmp/sysupgrade.img
-		IMAGE=/tmp/sysupgrade.img
-		;;
-esac
-
-export ARGV="$IMAGE"
-export ARGC=1
-
 for check in $sysupgrade_image_check; do
-	( $check "$IMAGE" ) || {
+	( eval "$check \"\$ARGV\"" ) || {
 		if [ $FORCE -eq 1 ]; then
-			echo "Image check '$check' failed but --force given - will update anyway!" >&2
+			echo "Image check '$check' failed but --force given - will update anyway!"
 			break
 		else
-			echo "Image check '$check' failed." >&2
+			echo "Image check '$check' failed."
 			exit 1
 		fi
 	}
@@ -336,17 +196,16 @@ if [ -n "$CONF_IMAGE" ]; then
 		# .gz files
 		1f8b) ;;
 		*)
-			echo "Invalid config file. Please use only .tar.gz files" >&2
+			echo "Invalid config file. Please use only .tar.gz files"
 			exit 1
 		;;
 	esac
 	get_image "$CONF_IMAGE" "cat" > "$CONF_TAR"
 	export SAVE_CONFIG=1
 elif ask_bool $SAVE_CONFIG "Keep config files over reflash"; then
-	[ $TEST -eq 1 ] || do_save_conffiles "$CONF_TAR"
+	[ $TEST -eq 1 ] || do_save_conffiles
 	export SAVE_CONFIG=1
 else
-	[ $TEST -eq 1 ] || rm -f "$CONF_TAR"
 	export SAVE_CONFIG=0
 fi
 
@@ -354,24 +213,28 @@ if [ $TEST -eq 1 ]; then
 	exit 0
 fi
 
-if [ $SAVE_PARTITIONS -eq 0 ]; then
-	touch /tmp/sysupgrade.always.overwrite.bootdisk.partmap
-else
-	rm -f /tmp/sysupgrade.always.overwrite.bootdisk.partmap
+run_hooks "" $sysupgrade_pre_upgrade
+
+# Some platforms/devices may want different sysupgrade process, e.g. without
+# killing processes yet or calling ubus system upgrade method.
+# This is needed e.g. on NAND devices where we just want to trigger stage1 at
+# this point.
+if type 'platform_pre_upgrade' >/dev/null 2>/dev/null; then
+	platform_pre_upgrade "$ARGV"
 fi
 
-install_bin /sbin/upgraded
-v "Commencing upgrade. Closing all shell sessions."
+ubus call system upgrade
+touch /tmp/sysupgrade
 
-COMMAND='. /lib/functions.sh; include /lib/upgrade; do_upgrade_stage2'
+if [ ! -f /tmp/failsafe ] ; then
+	kill_remaining TERM
+	sleep 3
+	kill_remaining KILL
+fi
 
-if [ -n "$FAILSAFE" ]; then
-	printf '%s\x00%s\x00%s' "$RAM_ROOT" "$IMAGE" "$COMMAND" >/tmp/sysupgrade
-	lock -u /tmp/.failsafe
+if [ -n "$(rootfs_type)" ]; then
+	v "Switching to ramdisk..."
+	run_ramfs '. /lib/functions.sh; include /lib/upgrade; do_upgrade'
 else
-	ubus call system sysupgrade "{
-		\"prefix\": $(json_string "$RAM_ROOT"),
-		\"path\": $(json_string "$IMAGE"),
-		\"command\": $(json_string "$COMMAND")
-	}"
+	do_upgrade
 fi
diff --git a/target/imagebuilder/files/Makefile b/target/imagebuilder/files/Makefile
--- a/target/imagebuilder/files/Makefile
+++ b/target/imagebuilder/files/Makefile
@@ -13,7 +13,7 @@ export TOPDIR LC_ALL LANG
 export OPENWRT_VERBOSE=s
 all: help
 
-export PATH:=$(TOPDIR)/staging_dir/host/bin:$(PATH)
+include $(TOPDIR)/include/host.mk
 
 ifneq ($(OPENWRT_BUILD),1)
   override OPENWRT_BUILD=1
@@ -23,7 +23,6 @@ endif
 include rules.mk
 include $(INCLUDE_DIR)/debug.mk
 include $(INCLUDE_DIR)/depends.mk
-include $(INCLUDE_DIR)/rootfs.mk
 
 include $(INCLUDE_DIR)/version.mk
 export REVISION
@@ -44,14 +43,6 @@ Building images:
 	make image PACKAGES="<pkg1> [<pkg2> [<pkg3> ...]]" # include extra packages
 	make image FILES="<path>" # include extra files from <path>
 	make image BIN_DIR="<path>" # alternative output directory for the images
-	make image EXTRA_IMAGE_NAME="<string>" # Add this to the output image filename (sanitized)
-
-Print manifest:
-	List "all" packages which get installed into the image.
-	You can use the following parameters:
-
-	make manifest PROFILE="<profilename>" # override the default target profile
-	make manifest PACKAGES="<pkg1> [<pkg2> [<pkg3> ...]]" # include extra packages
 
 endef
 $(eval $(call shexport,Helptext))
@@ -62,36 +53,37 @@ help: FORCE
 
 # override variables from rules.mk
 PACKAGE_DIR:=$(TOPDIR)/packages
-LISTS_DIR:=$(subst $(space),/,$(patsubst %,..,$(subst /,$(space),$(TARGET_DIR))))$(DL_DIR)
-OPKG:=$(call opkg,$(TARGET_DIR)) \
+OPKG:= \
+  IPKG_NO_SCRIPT=1 \
+  IPKG_TMP="$(TMP_DIR)/ipkgtmp" \
+  IPKG_INSTROOT="$(TARGET_DIR)" \
+  IPKG_CONF_DIR="$(TMP_DIR)" \
+  IPKG_OFFLINE_ROOT="$(TARGET_DIR)" \
+  $(STAGING_DIR_HOST)/bin/opkg \
 	-f $(TOPDIR)/repositories.conf \
+	--force-depends \
+	--force-overwrite \
+	--force-postinstall \
 	--cache $(DL_DIR) \
-	--lists-dir $(LISTS_DIR)
+	--offline-root $(TARGET_DIR) \
+	--add-dest root:/ \
+	--add-arch all:100 \
+	--add-arch $(ARCH_PACKAGES):200
+
+define Profile
+  $(eval $(call Profile/Default))
+  $(eval $(call Profile/$(1)))
+  ifeq ($(USER_PROFILE),)
+    USER_PROFILE:=$(1)
+  endif
+  $(1)_NAME:=$(NAME)
+  $(1)_PACKAGES:=$(PACKAGES)
+  PROFILE_NAMES += $(1)
+  PROFILE_LIST += \
+  	echo '$(1):'; [ -z '$(NAME)' ] || echo '	$(NAME)'; echo '	Packages: $(PACKAGES)';
+endef
 
 include $(INCLUDE_DIR)/target.mk
--include .profiles.mk
-
-USER_PROFILE ?= $(firstword $(PROFILE_NAMES))
-PROFILE_LIST = $(foreach p,$(PROFILE_NAMES), \
-	echo '$(patsubst DEVICE_%,%,$(p)):'; $(if $($(p)_NAME),echo '    $(subst ','"'"',$($(p)_NAME))'; ) echo '    Packages: $($(p)_PACKAGES)'; \
-)
-
-.profiles.mk: .targetinfo
-	@$(SCRIPT_DIR)/target-metadata.pl profile_mk $< '$(BOARD)$(if $(SUBTARGET),/$(SUBTARGET))' > $@
-
-staging_dir/host/.prereq-build: include/prereq-build.mk
-	mkdir -p tmp
-	@$(_SINGLE)$(NO_TRACE_MAKE) -j1 -r -s -f $(TOPDIR)/include/prereq-build.mk prereq 2>/dev/null || { \
-		echo "Prerequisite check failed. Use FORCE=1 to override."; \
-		false; \
-	}
-  ifneq ($(realpath $(TOPDIR)/include/prepare.mk),)
-	@$(_SINGLE)$(NO_TRACE_MAKE) -j1 -r -s -f $(TOPDIR)/include/prepare.mk prepare 2>/dev/null || { \
-		echo "Preparation failed."; \
-		false; \
-	}
-  endif
-	touch $@
 
 _call_info: FORCE
 	echo 'Current Target: "$(BOARD)$(if $(SUBTARGET), ($(BOARDNAME)))"'
@@ -99,51 +91,39 @@ _call_info: FORCE
 	echo 'Available Profiles:'
 	echo; $(PROFILE_LIST)
 
-BUILD_PACKAGES:=$(USER_PACKAGES) $(sort $(DEFAULT_PACKAGES) $($(USER_PROFILE)_PACKAGES) kernel)
+BUILD_PACKAGES:=$(sort $(DEFAULT_PACKAGES) $(USER_PACKAGES) $($(USER_PROFILE)_PACKAGES) kernel)
 # "-pkgname" in the package list means remove "pkgname" from the package list
 BUILD_PACKAGES:=$(filter-out $(filter -%,$(BUILD_PACKAGES)) $(patsubst -%,%,$(filter -%,$(BUILD_PACKAGES))),$(BUILD_PACKAGES))
 PACKAGES:=
 
-_call_image: staging_dir/host/.prereq-build
+_call_image:
 	echo 'Building images for $(BOARD)$(if $($(USER_PROFILE)_NAME), - $($(USER_PROFILE)_NAME))'
 	echo 'Packages: $(BUILD_PACKAGES)'
 	echo
-	rm -rf $(TARGET_DIR) $(TARGET_DIR_ORIG)
-	mkdir -p $(TARGET_DIR) $(BIN_DIR) $(TMP_DIR) $(DL_DIR)
-	$(MAKE) package_reload
-	$(MAKE) package_install
-	$(MAKE) -s prepare_rootfs
-	$(MAKE) -s build_image
-	$(MAKE) -s checksum
-
-_call_manifest: FORCE
 	rm -rf $(TARGET_DIR)
 	mkdir -p $(TARGET_DIR) $(BIN_DIR) $(TMP_DIR) $(DL_DIR)
-	$(MAKE) package_reload >/dev/null
-	$(MAKE) package_install >/dev/null
-	$(OPKG) list-installed
-
-package_index: FORCE
-	@echo >&2
-	@echo Building package index... >&2
-	@mkdir -p $(TMP_DIR) $(TARGET_DIR)/tmp
-	(cd $(PACKAGE_DIR); $(SCRIPT_DIR)/ipkg-make-index.sh . > Packages && \
-		gzip -9nc Packages > Packages.gz \
-	) >/dev/null 2>/dev/null
-	$(OPKG) update >&2 || true
-
-package_reload:
 	if [ ! -f "$(PACKAGE_DIR)/Packages" ] || [ ! -f "$(PACKAGE_DIR)/Packages.gz" ] || [ "`find $(PACKAGE_DIR) -cnewer $(PACKAGE_DIR)/Packages.gz`" ]; then \
-		echo "Package list missing or not up-to-date, generating it." >&2 ;\
+		echo "Package list missing or not up-to-date, generating it.";\
 		$(MAKE) package_index; \
 	else \
 		mkdir -p $(TARGET_DIR)/tmp; \
-		$(OPKG) update >&2 || true; \
+		$(OPKG) update || true; \
 	fi
+	$(MAKE) package_install
+ifneq ($(USER_FILES),)
+	$(MAKE) copy_files
+endif
+	$(MAKE) package_postinst
+	$(MAKE) build_image
 
-package_list: FORCE
-	@$(MAKE) -s package_reload
-	@$(OPKG) list --size 2>/dev/null
+package_index: FORCE
+	@echo
+	@echo Building package index...
+	@mkdir -p $(TMP_DIR) $(TARGET_DIR)/tmp
+	(cd $(PACKAGE_DIR); $(SCRIPT_DIR)/ipkg-make-index.sh . > Packages && \
+		gzip -9c Packages > Packages.gz \
+	) >/dev/null 2>/dev/null
+	$(OPKG) update || true
 
 package_install: FORCE
 	@echo
@@ -151,24 +131,34 @@ package_install: FORCE
 	$(OPKG) install $(firstword $(wildcard $(PACKAGE_DIR)/libc_*.ipk $(PACKAGE_DIR)/base/libc_*.ipk))
 	$(OPKG) install $(firstword $(wildcard $(PACKAGE_DIR)/kernel_*.ipk $(PACKAGE_DIR)/base/kernel_*.ipk))
 	$(OPKG) install $(BUILD_PACKAGES)
+	rm -f $(TARGET_DIR)/usr/lib/opkg/lists/*
 
-prepare_rootfs: FORCE
+copy_files: FORCE
 	@echo
-	@echo Finalizing root filesystem...
+	@echo Copying extra files
+	@$(call file_copy,$(USER_FILES)/*,$(TARGET_DIR)/)
 
-	$(CP) $(TARGET_DIR) $(TARGET_DIR_ORIG)
-	$(call prepare_rootfs,$(TARGET_DIR),$(USER_FILES))
+package_postinst: FORCE
+	@echo
+	@echo Cleaning up
+	@rm -f $(TARGET_DIR)/tmp/opkg.lock
+	@echo
+	@echo Activating init scripts
+	@mkdir -p $(TARGET_DIR)/etc/rc.d
+	@( \
+		cd $(TARGET_DIR); \
+		for script in ./usr/lib/opkg/info/*.postinst; do \
+			IPKG_INSTROOT=$(TARGET_DIR) $$(which bash) $$script; \
+		done || true \
+	)
+	rm -f $(TARGET_DIR)/usr/lib/opkg/info/*.postinst
+	$(if $(CONFIG_CLEAN_IPKG),rm -rf $(TARGET_DIR)/usr/lib/opkg)
 
 build_image: FORCE
 	@echo
 	@echo Building images...
-	$(NO_TRACE_MAKE) -C target/linux/$(BOARD)/image install TARGET_BUILD=1 IB=1 EXTRA_IMAGE_NAME="$(EXTRA_IMAGE_NAME)" \
+	$(NO_TRACE_MAKE) -C target/linux/$(BOARD)/image install TARGET_BUILD=1 IB=1 \
 		$(if $(USER_PROFILE),PROFILE="$(USER_PROFILE)")
-
-checksum: FORCE
-	@echo
-	@echo Calculating checksums...
-	@$(call sha256sums,$(BIN_DIR))
 
 clean:
 	rm -rf $(TMP_DIR) $(DL_DIR) $(TARGET_DIR) $(BIN_DIR)
@@ -177,31 +167,20 @@ clean:
 info:
 	(unset PROFILE FILES PACKAGES MAKEFLAGS; $(MAKE) -s _call_info)
 
-PROFILE_FILTER = $(filter DEVICE_$(PROFILE) $(PROFILE),$(PROFILE_NAMES))
-
-_check_profile: FORCE
+image:
 ifneq ($(PROFILE),)
-  ifeq ($(PROFILE_FILTER),)
+  ifeq ($(filter $(PROFILE),$(PROFILE_NAMES)),)
 	@echo 'Profile "$(PROFILE)" does not exist!'
 	@echo 'Use "make info" to get a list of available profile names.'
 	@exit 1
   endif
 endif
-
-image:
-	$(MAKE) -s _check_profile
 	(unset PROFILE FILES PACKAGES MAKEFLAGS; \
-	$(MAKE) -s _call_image \
-		$(if $(PROFILE),USER_PROFILE="$(PROFILE_FILTER)") \
+	$(MAKE) _call_image \
+		$(if $(PROFILE),USER_PROFILE="$(PROFILE)") \
 		$(if $(FILES),USER_FILES="$(FILES)") \
 		$(if $(PACKAGES),USER_PACKAGES="$(PACKAGES)") \
 		$(if $(BIN_DIR),BIN_DIR="$(BIN_DIR)"))
 
-manifest: FORCE
-	$(MAKE) -s _check_profile
-	(unset PROFILE FILES PACKAGES MAKEFLAGS; \
-	$(MAKE) -s _call_manifest \
-		$(if $(PROFILE),USER_PROFILE="$(PROFILE_FILTER)") \
-		$(if $(PACKAGES),USER_PACKAGES="$(PACKAGES)"))
+.SILENT: help info image
 
-.SILENT: help info image manifest
